{% set name = "librdkafka" %}
{% set version = "0.9.3" %}
{% set sha256 = "745ead036f0d5b732e1cd035a1f31fc23665f2982bf9d799742034e0a1bd0be9" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/edenhill/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # [win]

requirements:
  build:
    - zlib 1.2.*
    - openssl 1.0.*
    - libgsasl  # [not osx]
    - lz4
  run:
    - zlib 1.2.*
    - openssl 1.0.*
    - libgsasl  # [not osx]
    - lz4

test:
  commands:
    - test -f ${PREFIX}/lib/librdkafka.so  # [linux]
    - test -f ${PREFIX}/lib/librdkafka++.so  # [linux]
    - test -f ${PREFIX}/lib/librdkafka.dylib  # [osx]
    - test -f ${PREFIX}/lib/librdkafka++.dylib  # [osx]

about:
  home: https://github.com/edenhill/librdkafka
  license: BSD 2-clause
  license_family: BSD
  summary: 'The Apache Kafka C/C++ client library'

extra:
  recipe-maintainers:
    - kwilcox
