travis:
  secure:
    BINSTAR_TOKEN: OJ00DoLvnegCHeTp0ECAPTCLRUkP17pcyMvJ7b0W6cQ67W72bdQI2boyyYvi5/2brNv1etr8AmwAiouNmXJHJ6OLrr/lIdNSq/048Gq5BWoADwO2oDlvbKiYY5iV3oFcAsga7RJCwegLHK+hQ96nsTSgBU6wgDY/iq27Ktx6C19Cm5J0fbuTHpfbN1FdvPvdGDuSYG7BFys5rYZOtQT+eQF2gm8AqGTn+CBALDTI0jCv47DoyxY0WrqRlMtGHm4586Uq9MST+gY7xoQmLeR9azVmmMzV8LiclSBzlQA+LVXTdU2yQkoCl4r8sc9E2Du/1JIJrDoD9F7YAIzKon8dbmPAnnOIJ5qy9KHy7vbRxLW2CuqQc84g1gJedMj0LzkpZYac+0WJzot+ro4mBB3YcbXuemLKtBKYbKxEHx8Luz6Njbw9X/bmDSnPSYrFfmbWbG4cBEcUDMy3RqA4kBdlLOEBoccxs2CvMwytake77spONHw6qfRSSMG9EU1nL9tWzLbiBMEqtB0xzv91CXhtcuWdHauMj4h3z1WbBQnB7W3T9+savlTYdSlymqbyFCEurVL87G9pGZrdXiI5qHZkh6oyLG0mBTUZ2JQ8+LcxZD7XRzoTIwovFKd431mlroT8UBsr+cuAhQC7fF+NG36ya0Tx78BMNCZYWc+bnGZeoOI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
