travis:
  secure:
    BINSTAR_TOKEN: MkLL+bL7bTWrulTier+Po4UP32+LLdCr3us2AcnK37LGjynOwkDtV0VqQpETyFH5ev6wKjzFwRodb19KZB/KPlwsRDB+kyVYsqVvA5xRP1WcA0jJQa4vr5qtLF5sGdLd3Mb6RMzgw4IQy5r2De0AOcstmby2Tnq7wMTGcqiZ8SUVOlB9N6/IANutAuqbLKw19nRg3kSOpWDPpuO/W17Olk5iEzSIU/jOcnYMdNKjl0wbI0jXltSirHfhY3G7mu3LosFXfdcadoB1iR73Mu/Rp8pceSegRrh2aGq5GxOuZwPZTZxhmHW20FsuetcvzaMPxvGfFabj/3bCkica0AGIk5of5uT1tsygJ1khiLIk4w6lMifW2NxQv2mmxnEGnGRlrsiDzQY3oG61vKO9ucElGZx0z0grKm9DbZ+0A0Vm34UXMELS5myY55zAb9lxAcyTsWnp4knNHjoCQIPCw2KEFZBUUlhNCCA9xy85pD657w6TL4bGaSYyGpkFMDtxxmQGnnOg+4ajvTh5BaIQhXNcGFQZSA1tGDL2FcSR2eG43zSCEggs0wTuz55B8v1xai+2g6CfC1n9e1U4IzrOoQAxw9AlYHF4A+/YafZ9LT2vPNcJ0Qqii2miwT9WS9jY/lYwMazJFR0tH9BWbzD3w0QJZzBGc3s92wlGzT4SriwAefs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
