travis:
  secure:
    BINSTAR_TOKEN: GkwMUyiHZ/UVBifMsPBttnnYXJlNySEgyNndRwR79LQhpaQPBzQW9jn4FxnFeSFI5OsQvNcITdp7lyMyVJYb8S4B+DUc2VEusaQlWbPIVAb1Aiv3V8E9c/NMrNqMbEl4IiM5bIQ8QnZQ1YN5V7s++iRKoOktXkQVzOUoxEXkXJC9Gubksnz2edfj0t0TOT0ImR7axS7IPaF+yZLMvBUo1NsafXFR+TYpeL9jH/LPsu4VwZXEZo9FD8+LgEj4SR0nHgSfhgH3xXx/LajqJcK/HM7UUPi3qTIh/Tm2K9M8rAE/QWFJlAtEwrKAtJaZEgnHKz11IACAmOryFgBhvpJWi3rOGfoTXMIJxX2seehduWHu7+PAdmmQ7L/HkMaHIQu2zCAe7VfCCoV9oCzbFkTqdMu/NN/7OA06EwLfgQ53GnMLetHmeX9E+KT5qb2CsvD6K06nWNDDAi6kWT6ycSJ0uIwTW5hzU2BcKb3Uhc9xGuW+aImZH1wpIMTAq69xMYV7Mh/o6Hee1MZ8VDY5Se3WWz346Y19C8XaBdb+JBaYG+rcdleAswBBzIV89BvCXtNzm3eYHtEed0oH9sSOPYRhM7LJgH9UnPkJc3LcBYSMcOlL42xDRddKtEV9VjXLcLUIW/AMBSmQIE6Podj2eiReDJWEOX1xlrMreYBSJMhWRRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
